# Generated by Django 4.2.13 on 2024-05-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('cv_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='cvs/')),
                ('structured_cv', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=255)),
                ('date_open', models.DateField()),
                ('date_close', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplied',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cv')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobdescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('features', models.JSONField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cv')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobdescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
