# Generated by Django 5.0.6 on 2024-05-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='firebase_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
